networks:
  ran-user-network:
services:
  users:
    container_name: ran-users-management-go
    build: .
    networks:
      - ran-user-network
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=:8080
      - DB_USERNAME=user
      - DB_PASSWORD=user
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user
      - REDIS_HOST=redis:6379
      - REDIS_USERNAME=user
      - REDIS_PASSWORD=user
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
  
  postgres:
    container_name: ran-users-management-pg
    image: postgres
    networks:
      - ran-user-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=user
    restart: no

  redis:
    container_name: ran-users-management-rd
    image: redis
    networks:
      - ran-user-network
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=user
